Past_Events_Filters
BrightMindEnrichment/StreetCareiOS pull request #30
Opened 2024-11-06 02:36 UTC by marianbme

2024-11-09 04:11 UTC, phillipsk requested changes

2024-11-09 04:11 UTC, phillipsk commented on StreetCare/StreetCare/Preview Content/Preview Assets.xcassets/EventEnums.swift
instead of adding a new file could you combine the data you have here with the existing EventEnums file located here: `StudioProjects/StreetCareiOS/StreetCare/StreetCare/EventEnums.swift`

2024-11-09 04:12 UTC, phillipsk commented
Could you update the UI to match the figma we have here
[https://www.figma.com/design/V5mIYvVRm7dAfZYesOWLBX/Street-Care-App-Design-(2023-updated)?node-id=5304-22860&t=P8bBmbCsySCvBHB6-4](https://www.figma.com/design/V5mIYvVRm7dAfZYesOWLBX/Street-Care-App-Design-%282023-updated%29?node-id=5304-22860&t=P8bBmbCsySCvBHB6-4)

2024-11-15 00:02 UTC, phillipsk requested changes
Try and update the UI to match figma

See comment
https://github.com/BrightMindEnrichment/StreetCareiOS/pull/30#issuecomment-2466036084

2024-11-15 00:02 UTC, phillipsk commented on StreetCare/StreetCare/Preview Content/Preview Assets.xcassets/EventEnums.swift
Remove this file, once you have removed it make sure the code work without it. This file duplicates the other EventEnums.swift file

2024-11-15 00:02 UTC, phillipsk commented on .DS_Store
Remove this file with `git rm --cached` research this git command and apply to this file. The .DS_Store file should not be added to any PR we don't want these files in our codebase

2024-11-18 23:36 UTC, marianbme commented
Deleted the files please check now. It works without the other EventEnums file.

2024-11-18 23:43 UTC, phillipsk approved these changes

2024-11-19 23:02 UTC, merged