Google maps
BrightMindEnrichment/StreetCareiOS pull request #31
Opened 2024-11-12 22:34 UTC by ameykanunje

Keep a note of what changes are required to make GoogleMaps work

2024-12-04 04:41 UTC, phillipsk requested changes

2025-02-01 04:17 UTC, phillipsk commented on StreetCare/StreetCare/Views/Screens/Visit Log/GoogleMaps/GoogleMapView.swift
> +            latitude: 42.333774, //37.38605,
defaults to Boston

2025-02-18 07:30 UTC, phillipsk commented
Google Maps API key documentation can be found in StreetCare iOS docs, retrieve API key from there and add to `Secrets.plist` file

2025-02-18 07:43 UTC, phillipsk commented on StreetCare/StreetCare/Views/Screens/Visit Log/GoogleMaps/GoogleMapView.swift
> +            latitude: 42.333774, //37.38605,
Defaults to nationwide US view

2025-02-20 02:16 UTC, marianbme requested changes
![Maps1](https://github.com/user-attachments/assets/ae3f862b-4973-4604-aa87-4db0964f3b36)
![Maps2](https://github.com/user-attachments/assets/1e275e52-063d-4725-801f-edbe2a3f714d)
![Maps3](https://github.com/user-attachments/assets/c8016d76-e91c-40d0-b054-c7eb74f8e66e)
Tried multiple times, maps did not load.

2025-02-20 02:18 UTC, marianbme commented
![Maps4](https://github.com/user-attachments/assets/cea00823-4167-479a-ac8b-b23cc75316cd)

2025-02-20 02:45 UTC, phillipsk commented
> ![Maps1](https://private-user-images.githubusercontent.com/181419804/414988194-ae3f862b-4973-4604-aa87-4db0964f3b36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwMTk3MDAsIm5iZiI6MTc0MDAxOTQwMCwicGF0aCI6Ii8xODE0MTk4MDQvNDE0OTg4MTk0LWFlM2Y4NjJiLTQ5NzMtNDYwNC1hYTg3LTRkYjA5NjRmM2IzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyMFQwMjQzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzAyNDgwN2Y0MjZkZDg4ZTgyMjk3MjZiNTQ4MjM5NjEzYTIwNTAzNDQzZTZmMTEyOTg0NmUwZjVlOWI4Y2Q3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0HWSX57G_Ek8SI-e2Qkto2HuaxH8Im5LhcLZQV89KDA) ![Maps2](https://private-user-images.githubusercontent.com/181419804/414988215-1e275e52-063d-4725-801f-edbe2a3f714d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwMTk3MDAsIm5iZiI6MTc0MDAxOTQwMCwicGF0aCI6Ii8xODE0MTk4MDQvNDE0OTg4MjE1LTFlMjc1ZTUyLTA2M2QtNDcyNS04MDFmLWVkYmUyYTNmNzE0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyMFQwMjQzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWRkZGFkZDIyYTBmMTMzNTA2NGU1ODAxMWU2MzE2ODRhODdjNTMxZGVlN2EyYjkxZjU4YWViM2IwNmIzNWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I8OgUfg7vOpEu5lGAWaodXTn6HfHuecfwYVROTfKaZs) ![Maps3](https://private-user-images.githubusercontent.com/181419804/414988232-c8016d76-e91c-40d0-b054-c7eb74f8e66e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwMTk3MDAsIm5iZiI6MTc0MDAxOTQwMCwicGF0aCI6Ii8xODE0MTk4MDQvNDE0OTg4MjMyLWM4MDE2ZDc2LWU5MWMtNDBkMC1iMDU0LWM3ZWI3NGY4ZTY2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyMFQwMjQzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTI1ODM4ZTgwYzVlZWIwYTliZTdjNTg0MWI4NWM5YTI4YTlkZDM0MmMzYzlhMDZiNWYyYTEyYjZmYmEzYjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1WRpXMjq_QBZz8HMcb7j5C8stfzZCjzQyxA5bgxmjgc) Tried multiple times, maps did not load.

Try again you need to add a Secrets.plist file and add the Api key from the iOS documentation

2025-02-21 00:45 UTC, marianbme requested changes
The map works now good.
![image](https://github.com/user-attachments/assets/db5a8ac3-a896-40f9-b535-2807743893a7)
Events(yellow markers) are not displayed.
![image](https://github.com/user-attachments/assets/d93cbf42-7401-48fb-b5ec-c549a2d0fef4)
Fetching events from wrong collection.
![image](https://github.com/user-attachments/assets/62ceaba0-7681-43ec-8289-b9b2edcae21d)
![image](https://github.com/user-attachments/assets/b2eb48a0-00b9-4647-9c69-2d704df540d2)
![image](https://github.com/user-attachments/assets/03020244-18fc-4ca1-98b9-c6245118cbc6)
![image](https://github.com/user-attachments/assets/aba2e87f-c134-4a81-bc85-381abd18d497)
![image](https://github.com/user-attachments/assets/1a67570d-8d46-4348-9439-4215efa0518a)
Most of the helprequests displayed are test events.(i think the marker colors are interchanged.)

2025-02-21 00:47 UTC, marianbme commented
Better to show one location with most events instead of whole US.

2025-03-07 03:43 UTC, phillipsk commented
> The map works now good. ![image](https://private-user-images.githubusercontent.com/181419804/415433708-db5a8ac3-a896-40f9-b535-2807743893a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzMTI3NTYsIm5iZiI6MTc0MTMxMjQ1NiwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDMzNzA4LWRiNWE4YWMzLWE4OTYtNDBmOS1iNTM1LTI4MDc3NDM4OTNhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QwMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDA4N2YwZjU5ZTI5YmZhODVkMTA2ODhmN2I5MGU5YzVkMmRjZDEyNjE3MTFjODc1ODU1MzE3ZDY2M2IxMGE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xPdBwLNo0e_s56dCgrJR51KrShWbfNlqUwleywMXH10) Events(yellow markers) are not displayed. ![image](https://private-user-images.githubusercontent.com/181419804/415433894-d93cbf42-7401-48fb-b5ec-c549a2d0fef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzMTI3NTYsIm5iZiI6MTc0MTMxMjQ1NiwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDMzODk0LWQ5M2NiZjQyLTc0MDEtNDhmYi1iNWVjLWM1NDlhMmQwZmVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QwMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzQzNjFhMjk5N2VhZTM5MjJmYjA2MDgxNGFiM2JjMjllODAxYmRiYmNiNTMwMTcwMWNkYjAwYTc0M2QyZmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._3pkY-1d538IQwceI0vLPYBzkRi4MfMU1mOSRl-dP0A) Fetching events from wrong collection. ![image](https://private-user-images.githubusercontent.com/181419804/415434218-62ceaba0-7681-43ec-8289-b9b2edcae21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzMTI3NTYsIm5iZiI6MTc0MTMxMjQ1NiwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDM0MjE4LTYyY2VhYmEwLTc2ODEtNDNlYy04Mjg5LWI5YjJlZGNhZTIxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QwMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzM0NjU0NzJhMDU2NTA3MzZjMTBmMGI4M2Q0ZmMyMDk4YTdiYzVmZjRmMmQ5N2ZjN2Y2YzNjYWEyYzkxYjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Gn1F9wBtnkicaxrkGhbyrU6-uIaQxFnhh-Y0r5-B9bI) ![image](https://private-user-images.githubusercontent.com/181419804/415434257-b2eb48a0-00b9-4647-9c69-2d704df540d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzMTI3NTYsIm5iZiI6MTc0MTMxMjQ1NiwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDM0MjU3LWIyZWI0OGEwLTAwYjktNDY0Ny05YzY5LTJkNzA0ZGY1NDBkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QwMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzViNDdjMGMxMDNiNDgzZjUzM2JlZmNkMTJiMzEwMzI5MjBhOTY0MTgyOTAwODVkMmM0Nzg5ZmQ4ZDBlODVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FomR_JXLqYQYmmbjxL7sQQ_Kgyek0MQ69Dzlk0NC1B4) ![image](https://private-user-images.githubusercontent.com/181419804/415434296-03020244-18fc-4ca1-98b9-c6245118cbc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzMTI3NTYsIm5iZiI6MTc0MTMxMjQ1NiwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDM0Mjk2LTAzMDIwMjQ0LTE4ZmMtNGNhMS05OGI5LWM2MjQ1MTE4Y2JjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QwMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTg4NjZmNTBjY2RiZjViNjVjMDU1OGZiYjU2NTk5YjdlZWYzMDg5N2IwOGM4YjM2MjljOTUyZTBmNjQyYzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wuShJAibqbnUMyx-ygRBjCfqA_HNLfevQ1aN9-6yRDg) ![image](https://private-user-images.githubusercontent.com/181419804/415434320-aba2e87f-c134-4a81-bc85-381abd18d497.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzMTI3NTYsIm5iZiI6MTc0MTMxMjQ1NiwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDM0MzIwLWFiYTJlODdmLWMxMzQtNGE4MS1iYzg1LTM4MWFiZDE4ZDQ5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QwMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGI2ZGMxZTIyM2MxMWE4YzNhZmJkNTMwZjcyNmY3MjM5ZmM4OWFhZjk1OTY1NjhiZTU2ZjFlN2M5OGI0M2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1mHgPmF4Bawi2OW4wEOmtyO_HBm206LygnnpW0oibM4) ![image](https://private-user-images.githubusercontent.com/181419804/415434353-1a67570d-8d46-4348-9439-4215efa0518a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEzMTI3NTYsIm5iZiI6MTc0MTMxMjQ1NiwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDM0MzUzLTFhNjc1NzBkLThkNDYtNDM0OC05NDM5LTQyMTVlZmEwNTE4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwN1QwMTU0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmM3Y2NiYjQ2MTJiMjA5MGUyMzg1Y2RiNjdjMTMyYjRhNTQ5MTViYzVlNzE0ZmQ0OWVjOWQ3OGNmNDg1OWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mG6UQfMlTVpBqxhhZaf1Ge-LaGbfjlgXviU_og4KBCw) Most of the helprequests displayed are test events.(i think the marker colors are interchanged.)

Android is referencing the `OutreachEvents` collection

https://github.com/BrightMindEnrichment/StreetCare/pull/123/files#diff-f0d7f2b2c564894fe53cddab7f60cb2dc4d977b560db26867a152272c5c80316R60

2025-03-11 08:38 UTC, phillipsk commented
> Better to show one location with most events instead of whole US.

Defaulting to Boston location

2025-03-11 08:38 UTC, phillipsk commented
> The map works now good. ![image](https://private-user-images.githubusercontent.com/181419804/415433708-db5a8ac3-a896-40f9-b535-2807743893a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2ODI1NDUsIm5iZiI6MTc0MTY4MjI0NSwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDMzNzA4LWRiNWE4YWMzLWE4OTYtNDBmOS1iNTM1LTI4MDc3NDM4OTNhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMVQwODM3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzE3M2RkOTgxNGVlNDlkOGYxNjNjMDgwYjBjZGNmMWI0YjY5OTM3OWY3MTA1M2FlOWIzZWI1ZWFhMjkzY2EzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9WkrAZLYz30o7HtUOMeDummMgRfVIMeHSjXKuHVNga0) Events(yellow markers) are not displayed. ![image](https://private-user-images.githubusercontent.com/181419804/415433894-d93cbf42-7401-48fb-b5ec-c549a2d0fef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2ODI1NDUsIm5iZiI6MTc0MTY4MjI0NSwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDMzODk0LWQ5M2NiZjQyLTc0MDEtNDhmYi1iNWVjLWM1NDlhMmQwZmVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMVQwODM3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWIzYWMxZGU0YjJjMTZkODc1ZTFiN2YzMzZiZTg1YjJkODdlYjI2ZjhkNzk2Y2NjZGQ5NWYyMzYyYzA3MmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E0V69BGlZ2Jt0U93RCvwTbhytlSa8a0rQe9zn8BsMwc) Fetching events from wrong collection. ![image](https://private-user-images.githubusercontent.com/181419804/415434218-62ceaba0-7681-43ec-8289-b9b2edcae21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2ODI1NDUsIm5iZiI6MTc0MTY4MjI0NSwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDM0MjE4LTYyY2VhYmEwLTc2ODEtNDNlYy04Mjg5LWI5YjJlZGNhZTIxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMVQwODM3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzBhN2ZlZGFmYTcxMTMwNmMzOTNlMGZkZDM3M2NlZDA1OGQ4MjIzMzg4YzVjZmNmZmVhYzE3OWRjMTExZTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KY4YE-0Plt8vy5tqj5Qmk7jjzSIlknQRTbcxyylO_ZQ) ![image](https://private-user-images.githubusercontent.com/181419804/415434257-b2eb48a0-00b9-4647-9c69-2d704df540d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2ODI1NDUsIm5iZiI6MTc0MTY4MjI0NSwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDM0MjU3LWIyZWI0OGEwLTAwYjktNDY0Ny05YzY5LTJkNzA0ZGY1NDBkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMVQwODM3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2Q0YTZkMmNiZTkxZmNiNDEzYTk2ZmQ2ODQ3OWQwYzhkN2JjNTI1MDRhMGJkNWI5ZjM1OTNlOTc1ODhlODkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AYZPqt0NJfSLp902I0dLHfQMBOEZXoX2gzn6lJroZHo) ![image](https://private-user-images.githubusercontent.com/181419804/415434296-03020244-18fc-4ca1-98b9-c6245118cbc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2ODI1NDUsIm5iZiI6MTc0MTY4MjI0NSwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDM0Mjk2LTAzMDIwMjQ0LTE4ZmMtNGNhMS05OGI5LWM2MjQ1MTE4Y2JjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMVQwODM3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTdlMjU0MzVlYjQ2ZTg3NTBmMDNhZjYzODYzN2Q5MThiYTJhZTVjM2QxMWRiODYzYzVlMDVlMjhjYmVlNzMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I4efd7MX84ZOcVGxb0CKSnbPPSZvm7OjzTZgUNJXtSg) ![image](https://private-user-images.githubusercontent.com/181419804/415434320-aba2e87f-c134-4a81-bc85-381abd18d497.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2ODI1NDUsIm5iZiI6MTc0MTY4MjI0NSwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDM0MzIwLWFiYTJlODdmLWMxMzQtNGE4MS1iYzg1LTM4MWFiZDE4ZDQ5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMVQwODM3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDY2YTZiNDUxZTc2ZjA3NzFlYmRmNmMwNmJiODE0MTc2OWQ1ZTQ5N2Q5MDk0MjQwNjhmNjM1MWJmMmM1NDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M5DvuDv2Li7-va7LE3QAQHY9kt4F6Hh1sh7yETUtrtA) ![image](https://private-user-images.githubusercontent.com/181419804/415434353-1a67570d-8d46-4348-9439-4215efa0518a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2ODI1NDUsIm5iZiI6MTc0MTY4MjI0NSwicGF0aCI6Ii8xODE0MTk4MDQvNDE1NDM0MzUzLTFhNjc1NzBkLThkNDYtNDM0OC05NDM5LTQyMTVlZmEwNTE4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMVQwODM3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWZmZTBlNTNkY2UyODM4MjZhMGRiODRmODZmZmJiZjcxYjg0NjhhN2RjMTk3ZDU0NjRmNmUwZTgwOTgyODgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EFzNPCSLBwZ-wH2D_2rUDz1o1WNJSn_sLROZMn7r598) Most of the helprequests displayed are test events.(i think the marker colors are interchanged.)

Addressed this: changed the query order

2025-03-11 21:51 UTC, marianbme reviewed
![image](https://github.com/user-attachments/assets/18643525-e13d-42f8-a578-ffbe282c4096)
Works fine, Events and helprequests are legit, is it possible to change the color to yellow,  to a more brighter yellow.

2025-03-14 22:03 UTC, marianbme approved these changes
Map works fine.

2025-03-14 22:07 UTC, merged