Marian outreachform backup
BrightMindEnrichment/StreetCareiOS pull request #38
Opened 2024-11-15 20:15 UTC by marianbme

2024-11-19 02:55 UTC, phillipsk requested changes

2024-11-19 22:30 UTC, phillipsk requested changes

2024-11-19 22:30 UTC, phillipsk commented on StreetCare/StreetCare/Views/Screens/OutreachFormView.swift
> +                                saveToFirestore()
When saving successfully or when discarding can you dismiss the previous view and return to the Community screen


Uploading Screen_recording_20241119_172927.mp4…

2024-11-19 23:59 UTC, marianbme commented
Committed the requested changes.

2024-11-20 01:50 UTC, marianbme commented
Reverted the Changes

2024-11-20 01:58 UTC, phillipsk approved these changes

2024-11-20 02:00 UTC, merged