Initial Commit
BrightMindEnrichment/StreetCareiOS pull request #41
Opened 2024-11-26 23:04 UTC by marianbme

2024-12-03 04:46 UTC, phillipsk requested changes

2024-12-03 04:46 UTC, phillipsk commented on StreetCare/StreetCare/Views/Screens/AddHelpRequestForm.swift
> +            .padding() // Padding inside the TextField for spacing
I noticed that there are a lot of comments throughout the code. While comments can be helpful for explaining complex logic, having too many comments might reduce readability and clutter the code. Ideally, the code itself should be self-explanatory where possible (through clear variable names, functions, and structure).

Perhaps we could remove or rephrase comments that are redundant or overly detailed, keeping only those that add real value or explain non-obvious logic.

2024-12-03 04:46 UTC, phillipsk commented
Please add a better title for this PR.

2024-12-04 20:12 UTC, marianbme commented
fixed the requested changes, please check and let me know

2024-12-06 03:43 UTC, phillipsk requested changes

2024-12-06 03:43 UTC, phillipsk commented on StreetCare/StreetCare/Views/Screens/AddHelpRequestForm.swift
> +        .padding(.top, -32)
change padding to        ` .padding(.top, 12)`

2024-12-06 14:54 UTC, phillipsk approved these changes

2024-12-06 14:54 UTC, merged