Binding Problem Solved
BrightMindEnrichment/StreetCareiOS pull request #42
Opened 2024-11-27 20:31 UTC by marianbme

2024-12-03 04:54 UTC, phillipsk commented on StreetCare/StreetCare/Views/Screens/OutreachFormView.swift
> +/*struct OutreachFormView: View {
Please remove the old code, don't leave it as a comment

2024-12-03 04:57 UTC, phillipsk commented on StreetCare/StreetCare/Views/Screens/OutreachFormView.swift
> +        }
Is the code for the select skills sheet and overlay missing? Please review the previous working code and ensure it's still carried over into your new changes

2024-12-03 04:57 UTC, phillipsk commented on .DS_Store
Remove this file

2024-12-03 04:58 UTC, phillipsk requested changes
Please review the previous working code and ensure it's still carried over into your new changes

2024-12-03 21:05 UTC, marianbme commented
Solved the issue, deleledted .DS store file and removed old code

2024-12-04 04:31 UTC, phillipsk requested changes

2024-12-04 04:31 UTC, phillipsk commented on StreetCare/StreetCare/Views/Screens/OutreachFormView.swift
>              alertMessage = "Event saved successfully!"
Does this alert message display after saving an event?

2024-12-04 04:31 UTC, phillipsk commented
Merge conflicts need to be resolved

2024-12-06 03:59 UTC, phillipsk requested changes
After a user successfully creates an outreach event an alert displays indicating the submission was successful
1) Update the alert message title to "New Outreach Event" remove generic `Message` placeholder text
<img width="256" alt="image" src="https://github.com/user-attachments/assets/4d0887c0-af62-4cc1-97b9-847395bfc3e1">


2) After the user taps OK the previous screen should be dismissed and user should return to the community view of help requests

2024-12-06 04:00 UTC, phillipsk commented
> `StreetCare/Pods/Manifest.lock`
> `StreetCare/Pods/Pods.xcodeproj/project.pbxproj`
> `StreetCare/Pods/Target Support Files/Pods-StreetCare/Pods-StreetCare.debug.xcconfig`
> `StreetCare/Pods/Target Support Files/Pods-StreetCare/Pods-StreetCare.release.xcconfig`

Try and resolve these merge conflicts

2024-12-06 15:37 UTC, phillipsk approved these changes

2024-12-06 15:50 UTC, merged